volumes:
  postgres-data:
    external: true
  pg-admin:
    external: true
services:
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_DNC_API: http://localhost:8000
      REACT_APP_USERS_API: http://localhost:8001
  postgres:
    build:
      context: ./db
      dockerfile: ./Dockerfile.dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_MULTIPLE_DATABASES=dnc,users
      - POSTGRES_PASSWORD=test-databases
    ports:
      - 15432:5432
  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: g7r@g7r.com
      PGADMIN_DEFAULT_PASSWORD: g7r
      PGADMIN_DISABLE_POSTFIX: 1
  dnc:
    build:
      context: ./dnc
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./dnc:/app
    environment:
      DATABASE_URL: postgresql://dnc:password@postgres/dnc
      WAIT_HOSTS: postgres:5432
      PORT: 8000
  user:
    build:
      context: ./user
      dockerfile: Dockerfile.dev
    ports:
      - 8001:8000
    volumes:
      - ./user:/app
    environment:
      DATABASE_URL: postgresql://users:password@postgres/users
      WAIT_HOSTS: postgres:5432
      PORT: 8001
